services:
  nWatch:
    container_name: nginxc
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
    - 80
    - 443
    image: lukastosic/apache-php-curl
    ports:
    - '80'
    - '443'
    volumes:
    - ./:/var/www/html
version: '3'
